<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Rohel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rohel.CargoNote</code>
 */
class CargoNote extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int32 cargo_id = 2;</code>
     */
    protected $cargo_id = 0;
    /**
     * Generated from protobuf field <code>int32 operator_id = 3;</code>
     */
    protected $operator_id = 0;
    /**
     * Generated from protobuf field <code>string note = 4;</code>
     */
    protected $note = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $cargo_id
     *     @type int $operator_id
     *     @type string $note
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cargo_id = 2;</code>
     * @return int
     */
    public function getCargoId()
    {
        return $this->cargo_id;
    }

    /**
     * Generated from protobuf field <code>int32 cargo_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCargoId($var)
    {
        GPBUtil::checkInt32($var);
        $this->cargo_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 operator_id = 3;</code>
     * @return int
     */
    public function getOperatorId()
    {
        return $this->operator_id;
    }

    /**
     * Generated from protobuf field <code>int32 operator_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOperatorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->operator_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string note = 4;</code>
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Generated from protobuf field <code>string note = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->note = $var;

        return $this;
    }

}

