<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Rohel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rohel.RequestUpdates</code>
 */
class RequestUpdates extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>bool operator = 2;</code>
     */
    protected $operator = false;
    /**
     * Generated from protobuf field <code>bool originator = 3;</code>
     */
    protected $originator = false;
    /**
     * Generated from protobuf field <code>bool client = 4;</code>
     */
    protected $client = false;
    /**
     * Generated from protobuf field <code>bool from_city = 5;</code>
     */
    protected $from_city = false;
    /**
     * Generated from protobuf field <code>bool from_address = 6;</code>
     */
    protected $from_address = false;
    /**
     * Generated from protobuf field <code>bool to_city = 7;</code>
     */
    protected $to_city = false;
    /**
     * Generated from protobuf field <code>bool to_address = 8;</code>
     */
    protected $to_address = false;
    /**
     * Generated from protobuf field <code>bool loading_date = 9;</code>
     */
    protected $loading_date = false;
    /**
     * Generated from protobuf field <code>bool unloading_date = 10;</code>
     */
    protected $unloading_date = false;
    /**
     * Generated from protobuf field <code>bool description = 11;</code>
     */
    protected $description = false;
    /**
     * Generated from protobuf field <code>bool collies = 12;</code>
     */
    protected $collies = false;
    /**
     * Generated from protobuf field <code>bool weight = 13;</code>
     */
    protected $weight = false;
    /**
     * Generated from protobuf field <code>bool volume = 14;</code>
     */
    protected $volume = false;
    /**
     * Generated from protobuf field <code>bool loading_meters = 15;</code>
     */
    protected $loading_meters = false;
    /**
     * Generated from protobuf field <code>bool freight = 16;</code>
     */
    protected $freight = false;
    /**
     * Generated from protobuf field <code>bool instructions = 17;</code>
     */
    protected $instructions = false;
    /**
     * Generated from protobuf field <code>bool acceptance = 18;</code>
     */
    protected $acceptance = false;
    /**
     * Generated from protobuf field <code>bool expiration = 19;</code>
     */
    protected $expiration = false;
    /**
     * Generated from protobuf field <code>bool plate_number = 20;</code>
     */
    protected $plate_number = false;
    /**
     * Generated from protobuf field <code>bool ameta = 21;</code>
     */
    protected $ameta = false;
    /**
     * Generated from protobuf field <code>bool order_type = 22;</code>
     */
    protected $order_type = false;
    /**
     * Generated from protobuf field <code>bool adr = 23;</code>
     */
    protected $adr = false;
    /**
     * Generated from protobuf field <code>bool recipient = 24;</code>
     */
    protected $recipient = false;
    /**
     * Generated from protobuf field <code>bool status = 25;</code>
     */
    protected $status = false;
    /**
     * Generated from protobuf field <code>bool accepted_by = 26;</code>
     */
    protected $accepted_by = false;
    /**
     * Generated from protobuf field <code>bool dimensions = 27;</code>
     */
    protected $dimensions = false;
    /**
     * Generated from protobuf field <code>bool package = 28;</code>
     */
    protected $package = false;
    /**
     * Generated from protobuf field <code>bool shipper = 29;</code>
     */
    protected $shipper = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type bool $operator
     *     @type bool $originator
     *     @type bool $client
     *     @type bool $from_city
     *     @type bool $from_address
     *     @type bool $to_city
     *     @type bool $to_address
     *     @type bool $loading_date
     *     @type bool $unloading_date
     *     @type bool $description
     *     @type bool $collies
     *     @type bool $weight
     *     @type bool $volume
     *     @type bool $loading_meters
     *     @type bool $freight
     *     @type bool $instructions
     *     @type bool $acceptance
     *     @type bool $expiration
     *     @type bool $plate_number
     *     @type bool $ameta
     *     @type bool $order_type
     *     @type bool $adr
     *     @type bool $recipient
     *     @type bool $status
     *     @type bool $accepted_by
     *     @type bool $dimensions
     *     @type bool $package
     *     @type bool $shipper
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool operator = 2;</code>
     * @return bool
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>bool operator = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkBool($var);
        $this->operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool originator = 3;</code>
     * @return bool
     */
    public function getOriginator()
    {
        return $this->originator;
    }

    /**
     * Generated from protobuf field <code>bool originator = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setOriginator($var)
    {
        GPBUtil::checkBool($var);
        $this->originator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool client = 4;</code>
     * @return bool
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>bool client = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setClient($var)
    {
        GPBUtil::checkBool($var);
        $this->client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool from_city = 5;</code>
     * @return bool
     */
    public function getFromCity()
    {
        return $this->from_city;
    }

    /**
     * Generated from protobuf field <code>bool from_city = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setFromCity($var)
    {
        GPBUtil::checkBool($var);
        $this->from_city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool from_address = 6;</code>
     * @return bool
     */
    public function getFromAddress()
    {
        return $this->from_address;
    }

    /**
     * Generated from protobuf field <code>bool from_address = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setFromAddress($var)
    {
        GPBUtil::checkBool($var);
        $this->from_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool to_city = 7;</code>
     * @return bool
     */
    public function getToCity()
    {
        return $this->to_city;
    }

    /**
     * Generated from protobuf field <code>bool to_city = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setToCity($var)
    {
        GPBUtil::checkBool($var);
        $this->to_city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool to_address = 8;</code>
     * @return bool
     */
    public function getToAddress()
    {
        return $this->to_address;
    }

    /**
     * Generated from protobuf field <code>bool to_address = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setToAddress($var)
    {
        GPBUtil::checkBool($var);
        $this->to_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool loading_date = 9;</code>
     * @return bool
     */
    public function getLoadingDate()
    {
        return $this->loading_date;
    }

    /**
     * Generated from protobuf field <code>bool loading_date = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setLoadingDate($var)
    {
        GPBUtil::checkBool($var);
        $this->loading_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool unloading_date = 10;</code>
     * @return bool
     */
    public function getUnloadingDate()
    {
        return $this->unloading_date;
    }

    /**
     * Generated from protobuf field <code>bool unloading_date = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setUnloadingDate($var)
    {
        GPBUtil::checkBool($var);
        $this->unloading_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool description = 11;</code>
     * @return bool
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>bool description = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkBool($var);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool collies = 12;</code>
     * @return bool
     */
    public function getCollies()
    {
        return $this->collies;
    }

    /**
     * Generated from protobuf field <code>bool collies = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setCollies($var)
    {
        GPBUtil::checkBool($var);
        $this->collies = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool weight = 13;</code>
     * @return bool
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>bool weight = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkBool($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool volume = 14;</code>
     * @return bool
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>bool volume = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkBool($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool loading_meters = 15;</code>
     * @return bool
     */
    public function getLoadingMeters()
    {
        return $this->loading_meters;
    }

    /**
     * Generated from protobuf field <code>bool loading_meters = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setLoadingMeters($var)
    {
        GPBUtil::checkBool($var);
        $this->loading_meters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool freight = 16;</code>
     * @return bool
     */
    public function getFreight()
    {
        return $this->freight;
    }

    /**
     * Generated from protobuf field <code>bool freight = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setFreight($var)
    {
        GPBUtil::checkBool($var);
        $this->freight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool instructions = 17;</code>
     * @return bool
     */
    public function getInstructions()
    {
        return $this->instructions;
    }

    /**
     * Generated from protobuf field <code>bool instructions = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setInstructions($var)
    {
        GPBUtil::checkBool($var);
        $this->instructions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool acceptance = 18;</code>
     * @return bool
     */
    public function getAcceptance()
    {
        return $this->acceptance;
    }

    /**
     * Generated from protobuf field <code>bool acceptance = 18;</code>
     * @param bool $var
     * @return $this
     */
    public function setAcceptance($var)
    {
        GPBUtil::checkBool($var);
        $this->acceptance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool expiration = 19;</code>
     * @return bool
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>bool expiration = 19;</code>
     * @param bool $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkBool($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool plate_number = 20;</code>
     * @return bool
     */
    public function getPlateNumber()
    {
        return $this->plate_number;
    }

    /**
     * Generated from protobuf field <code>bool plate_number = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setPlateNumber($var)
    {
        GPBUtil::checkBool($var);
        $this->plate_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ameta = 21;</code>
     * @return bool
     */
    public function getAmeta()
    {
        return $this->ameta;
    }

    /**
     * Generated from protobuf field <code>bool ameta = 21;</code>
     * @param bool $var
     * @return $this
     */
    public function setAmeta($var)
    {
        GPBUtil::checkBool($var);
        $this->ameta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool order_type = 22;</code>
     * @return bool
     */
    public function getOrderType()
    {
        return $this->order_type;
    }

    /**
     * Generated from protobuf field <code>bool order_type = 22;</code>
     * @param bool $var
     * @return $this
     */
    public function setOrderType($var)
    {
        GPBUtil::checkBool($var);
        $this->order_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool adr = 23;</code>
     * @return bool
     */
    public function getAdr()
    {
        return $this->adr;
    }

    /**
     * Generated from protobuf field <code>bool adr = 23;</code>
     * @param bool $var
     * @return $this
     */
    public function setAdr($var)
    {
        GPBUtil::checkBool($var);
        $this->adr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool recipient = 24;</code>
     * @return bool
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     * Generated from protobuf field <code>bool recipient = 24;</code>
     * @param bool $var
     * @return $this
     */
    public function setRecipient($var)
    {
        GPBUtil::checkBool($var);
        $this->recipient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool status = 25;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>bool status = 25;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool accepted_by = 26;</code>
     * @return bool
     */
    public function getAcceptedBy()
    {
        return $this->accepted_by;
    }

    /**
     * Generated from protobuf field <code>bool accepted_by = 26;</code>
     * @param bool $var
     * @return $this
     */
    public function setAcceptedBy($var)
    {
        GPBUtil::checkBool($var);
        $this->accepted_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool dimensions = 27;</code>
     * @return bool
     */
    public function getDimensions()
    {
        return $this->dimensions;
    }

    /**
     * Generated from protobuf field <code>bool dimensions = 27;</code>
     * @param bool $var
     * @return $this
     */
    public function setDimensions($var)
    {
        GPBUtil::checkBool($var);
        $this->dimensions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool package = 28;</code>
     * @return bool
     */
    public function getPackage()
    {
        return $this->package;
    }

    /**
     * Generated from protobuf field <code>bool package = 28;</code>
     * @param bool $var
     * @return $this
     */
    public function setPackage($var)
    {
        GPBUtil::checkBool($var);
        $this->package = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool shipper = 29;</code>
     * @return bool
     */
    public function getShipper()
    {
        return $this->shipper;
    }

    /**
     * Generated from protobuf field <code>bool shipper = 29;</code>
     * @param bool $var
     * @return $this
     */
    public function setShipper($var)
    {
        GPBUtil::checkBool($var);
        $this->shipper = $var;

        return $this;
    }

}

