<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Rohel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rohel.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string operator = 2;</code>
     */
    protected $operator = '';
    /**
     * Generated from protobuf field <code>int32 originator = 3;</code>
     */
    protected $originator = 0;
    /**
     * Generated from protobuf field <code>string client = 4;</code>
     */
    protected $client = '';
    /**
     * Generated from protobuf field <code>string from_city = 5;</code>
     */
    protected $from_city = '';
    /**
     * Generated from protobuf field <code>string from_address = 6;</code>
     */
    protected $from_address = '';
    /**
     * Generated from protobuf field <code>string to_city = 7;</code>
     */
    protected $to_city = '';
    /**
     * Generated from protobuf field <code>string to_address = 8;</code>
     */
    protected $to_address = '';
    /**
     * Generated from protobuf field <code>uint64 loading_date = 9;</code>
     */
    protected $loading_date = 0;
    /**
     * Generated from protobuf field <code>uint64 unloading_date = 10;</code>
     */
    protected $unloading_date = 0;
    /**
     * Generated from protobuf field <code>string description = 11;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string collies = 12;</code>
     */
    protected $collies = '';
    /**
     * Generated from protobuf field <code>float weight = 13;</code>
     */
    protected $weight = 0.0;
    /**
     * Generated from protobuf field <code>float volume = 14;</code>
     */
    protected $volume = 0.0;
    /**
     * Generated from protobuf field <code>float loading_meters = 15;</code>
     */
    protected $loading_meters = 0.0;
    /**
     * Generated from protobuf field <code>float freight = 16;</code>
     */
    protected $freight = 0.0;
    /**
     * Generated from protobuf field <code>string instructions = 17;</code>
     */
    protected $instructions = '';
    /**
     * Generated from protobuf field <code>uint64 acceptance = 18;</code>
     */
    protected $acceptance = 0;
    /**
     * Generated from protobuf field <code>uint64 expiration = 19;</code>
     */
    protected $expiration = 0;
    /**
     * Generated from protobuf field <code>string plate_number = 20;</code>
     */
    protected $plate_number = '';
    /**
     * Generated from protobuf field <code>string ameta = 21;</code>
     */
    protected $ameta = '';
    /**
     * Generated from protobuf field <code>string order_type = 22;</code>
     */
    protected $order_type = '';
    /**
     * Generated from protobuf field <code>string adr = 23;</code>
     */
    protected $adr = '';
    /**
     * Generated from protobuf field <code>int32 recipient = 24;</code>
     */
    protected $recipient = 0;
    /**
     * Generated from protobuf field <code>int32 status = 25;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int32 accepted_by = 26;</code>
     */
    protected $accepted_by = 0;
    /**
     * Generated from protobuf field <code>uint64 creation_date = 27;</code>
     */
    protected $creation_date = 0;
    /**
     * Generated from protobuf field <code>uint64 update_date = 28;</code>
     */
    protected $update_date = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $operator
     *     @type int $originator
     *     @type string $client
     *     @type string $from_city
     *     @type string $from_address
     *     @type string $to_city
     *     @type string $to_address
     *     @type int|string $loading_date
     *     @type int|string $unloading_date
     *     @type string $description
     *     @type string $collies
     *     @type float $weight
     *     @type float $volume
     *     @type float $loading_meters
     *     @type float $freight
     *     @type string $instructions
     *     @type int|string $acceptance
     *     @type int|string $expiration
     *     @type string $plate_number
     *     @type string $ameta
     *     @type string $order_type
     *     @type string $adr
     *     @type int $recipient
     *     @type int $status
     *     @type int $accepted_by
     *     @type int|string $creation_date
     *     @type int|string $update_date
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operator = 2;</code>
     * @return string
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>string operator = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 originator = 3;</code>
     * @return int
     */
    public function getOriginator()
    {
        return $this->originator;
    }

    /**
     * Generated from protobuf field <code>int32 originator = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginator($var)
    {
        GPBUtil::checkInt32($var);
        $this->originator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client = 4;</code>
     * @return string
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>string client = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setClient($var)
    {
        GPBUtil::checkString($var, True);
        $this->client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from_city = 5;</code>
     * @return string
     */
    public function getFromCity()
    {
        return $this->from_city;
    }

    /**
     * Generated from protobuf field <code>string from_city = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFromCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->from_city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from_address = 6;</code>
     * @return string
     */
    public function getFromAddress()
    {
        return $this->from_address;
    }

    /**
     * Generated from protobuf field <code>string from_address = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFromAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->from_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to_city = 7;</code>
     * @return string
     */
    public function getToCity()
    {
        return $this->to_city;
    }

    /**
     * Generated from protobuf field <code>string to_city = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to_address = 8;</code>
     * @return string
     */
    public function getToAddress()
    {
        return $this->to_address;
    }

    /**
     * Generated from protobuf field <code>string to_address = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setToAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 loading_date = 9;</code>
     * @return int|string
     */
    public function getLoadingDate()
    {
        return $this->loading_date;
    }

    /**
     * Generated from protobuf field <code>uint64 loading_date = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLoadingDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->loading_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 unloading_date = 10;</code>
     * @return int|string
     */
    public function getUnloadingDate()
    {
        return $this->unloading_date;
    }

    /**
     * Generated from protobuf field <code>uint64 unloading_date = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUnloadingDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->unloading_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 11;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collies = 12;</code>
     * @return string
     */
    public function getCollies()
    {
        return $this->collies;
    }

    /**
     * Generated from protobuf field <code>string collies = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCollies($var)
    {
        GPBUtil::checkString($var, True);
        $this->collies = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float weight = 13;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>float weight = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float volume = 14;</code>
     * @return float
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>float volume = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkFloat($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float loading_meters = 15;</code>
     * @return float
     */
    public function getLoadingMeters()
    {
        return $this->loading_meters;
    }

    /**
     * Generated from protobuf field <code>float loading_meters = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setLoadingMeters($var)
    {
        GPBUtil::checkFloat($var);
        $this->loading_meters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float freight = 16;</code>
     * @return float
     */
    public function getFreight()
    {
        return $this->freight;
    }

    /**
     * Generated from protobuf field <code>float freight = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setFreight($var)
    {
        GPBUtil::checkFloat($var);
        $this->freight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string instructions = 17;</code>
     * @return string
     */
    public function getInstructions()
    {
        return $this->instructions;
    }

    /**
     * Generated from protobuf field <code>string instructions = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setInstructions($var)
    {
        GPBUtil::checkString($var, True);
        $this->instructions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 acceptance = 18;</code>
     * @return int|string
     */
    public function getAcceptance()
    {
        return $this->acceptance;
    }

    /**
     * Generated from protobuf field <code>uint64 acceptance = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAcceptance($var)
    {
        GPBUtil::checkUint64($var);
        $this->acceptance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expiration = 19;</code>
     * @return int|string
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>uint64 expiration = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkUint64($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string plate_number = 20;</code>
     * @return string
     */
    public function getPlateNumber()
    {
        return $this->plate_number;
    }

    /**
     * Generated from protobuf field <code>string plate_number = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setPlateNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->plate_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ameta = 21;</code>
     * @return string
     */
    public function getAmeta()
    {
        return $this->ameta;
    }

    /**
     * Generated from protobuf field <code>string ameta = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setAmeta($var)
    {
        GPBUtil::checkString($var, True);
        $this->ameta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_type = 22;</code>
     * @return string
     */
    public function getOrderType()
    {
        return $this->order_type;
    }

    /**
     * Generated from protobuf field <code>string order_type = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderType($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string adr = 23;</code>
     * @return string
     */
    public function getAdr()
    {
        return $this->adr;
    }

    /**
     * Generated from protobuf field <code>string adr = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setAdr($var)
    {
        GPBUtil::checkString($var, True);
        $this->adr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 recipient = 24;</code>
     * @return int
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     * Generated from protobuf field <code>int32 recipient = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setRecipient($var)
    {
        GPBUtil::checkInt32($var);
        $this->recipient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 25;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 accepted_by = 26;</code>
     * @return int
     */
    public function getAcceptedBy()
    {
        return $this->accepted_by;
    }

    /**
     * Generated from protobuf field <code>int32 accepted_by = 26;</code>
     * @param int $var
     * @return $this
     */
    public function setAcceptedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->accepted_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 creation_date = 27;</code>
     * @return int|string
     */
    public function getCreationDate()
    {
        return $this->creation_date;
    }

    /**
     * Generated from protobuf field <code>uint64 creation_date = 27;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreationDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->creation_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 update_date = 28;</code>
     * @return int|string
     */
    public function getUpdateDate()
    {
        return $this->update_date;
    }

    /**
     * Generated from protobuf field <code>uint64 update_date = 28;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->update_date = $var;

        return $this;
    }

}

