<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Rohel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rohel.Truck</code>
 */
class Truck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string operator = 2;</code>
     */
    protected $operator = '';
    /**
     * Generated from protobuf field <code>int32 originator = 3;</code>
     */
    protected $originator = 0;
    /**
     * Generated from protobuf field <code>int32 recipient = 4;</code>
     */
    protected $recipient = 0;
    /**
     * Generated from protobuf field <code>int32 accepted_by = 5;</code>
     */
    protected $accepted_by = 0;
    /**
     * Generated from protobuf field <code>int32 status = 6;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string from_city = 7;</code>
     */
    protected $from_city = '';
    /**
     * Generated from protobuf field <code>string from_address = 8;</code>
     */
    protected $from_address = '';
    /**
     * Generated from protobuf field <code>uint64 loading_date = 9;</code>
     */
    protected $loading_date = 0;
    /**
     * Generated from protobuf field <code>uint64 unloading_date = 10;</code>
     */
    protected $unloading_date = 0;
    /**
     * Generated from protobuf field <code>uint64 availability = 11;</code>
     */
    protected $availability = 0;
    /**
     * Generated from protobuf field <code>uint64 acceptance = 12;</code>
     */
    protected $acceptance = 0;
    /**
     * Generated from protobuf field <code>uint64 expiration = 13;</code>
     */
    protected $expiration = 0;
    /**
     * Generated from protobuf field <code>string details = 14;</code>
     */
    protected $details = '';
    /**
     * Generated from protobuf field <code>float freight = 15;</code>
     */
    protected $freight = 0.0;
    /**
     * Generated from protobuf field <code>string plate_number = 16;</code>
     */
    protected $plate_number = '';
    /**
     * Generated from protobuf field <code>string ameta = 17;</code>
     */
    protected $ameta = '';
    /**
     * Generated from protobuf field <code>uint64 update_date = 18;</code>
     */
    protected $update_date = 0;
    /**
     * Generated from protobuf field <code>string cargo_type = 19;</code>
     */
    protected $cargo_type = '';
    /**
     * Generated from protobuf field <code>string truck_type = 20;</code>
     */
    protected $truck_type = '';
    /**
     * Generated from protobuf field <code>string contract_type = 21;</code>
     */
    protected $contract_type = '';
    /**
     * Generated from protobuf field <code>string adr = 22;</code>
     */
    protected $adr = '';
    /**
     * Generated from protobuf field <code>repeated .Rohel.TruckStop stop = 23;</code>
     */
    private $stop;
    /**
     * Generated from protobuf field <code>uint64 creation_date = 24;</code>
     */
    protected $creation_date = 0;
    /**
     * Generated from protobuf field <code>int32 status_changed_by = 25;</code>
     */
    protected $status_changed_by = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $operator
     *     @type int $originator
     *     @type int $recipient
     *     @type int $accepted_by
     *     @type int $status
     *     @type string $from_city
     *     @type string $from_address
     *     @type int|string $loading_date
     *     @type int|string $unloading_date
     *     @type int|string $availability
     *     @type int|string $acceptance
     *     @type int|string $expiration
     *     @type string $details
     *     @type float $freight
     *     @type string $plate_number
     *     @type string $ameta
     *     @type int|string $update_date
     *     @type string $cargo_type
     *     @type string $truck_type
     *     @type string $contract_type
     *     @type string $adr
     *     @type \Rohel\TruckStop[]|\Google\Protobuf\Internal\RepeatedField $stop
     *     @type int|string $creation_date
     *     @type int $status_changed_by
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operator = 2;</code>
     * @return string
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>string operator = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 originator = 3;</code>
     * @return int
     */
    public function getOriginator()
    {
        return $this->originator;
    }

    /**
     * Generated from protobuf field <code>int32 originator = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginator($var)
    {
        GPBUtil::checkInt32($var);
        $this->originator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 recipient = 4;</code>
     * @return int
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     * Generated from protobuf field <code>int32 recipient = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRecipient($var)
    {
        GPBUtil::checkInt32($var);
        $this->recipient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 accepted_by = 5;</code>
     * @return int
     */
    public function getAcceptedBy()
    {
        return $this->accepted_by;
    }

    /**
     * Generated from protobuf field <code>int32 accepted_by = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAcceptedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->accepted_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 6;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from_city = 7;</code>
     * @return string
     */
    public function getFromCity()
    {
        return $this->from_city;
    }

    /**
     * Generated from protobuf field <code>string from_city = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFromCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->from_city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from_address = 8;</code>
     * @return string
     */
    public function getFromAddress()
    {
        return $this->from_address;
    }

    /**
     * Generated from protobuf field <code>string from_address = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFromAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->from_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 loading_date = 9;</code>
     * @return int|string
     */
    public function getLoadingDate()
    {
        return $this->loading_date;
    }

    /**
     * Generated from protobuf field <code>uint64 loading_date = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLoadingDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->loading_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 unloading_date = 10;</code>
     * @return int|string
     */
    public function getUnloadingDate()
    {
        return $this->unloading_date;
    }

    /**
     * Generated from protobuf field <code>uint64 unloading_date = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUnloadingDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->unloading_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 availability = 11;</code>
     * @return int|string
     */
    public function getAvailability()
    {
        return $this->availability;
    }

    /**
     * Generated from protobuf field <code>uint64 availability = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAvailability($var)
    {
        GPBUtil::checkUint64($var);
        $this->availability = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 acceptance = 12;</code>
     * @return int|string
     */
    public function getAcceptance()
    {
        return $this->acceptance;
    }

    /**
     * Generated from protobuf field <code>uint64 acceptance = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAcceptance($var)
    {
        GPBUtil::checkUint64($var);
        $this->acceptance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expiration = 13;</code>
     * @return int|string
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>uint64 expiration = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkUint64($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string details = 14;</code>
     * @return string
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>string details = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkString($var, True);
        $this->details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float freight = 15;</code>
     * @return float
     */
    public function getFreight()
    {
        return $this->freight;
    }

    /**
     * Generated from protobuf field <code>float freight = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setFreight($var)
    {
        GPBUtil::checkFloat($var);
        $this->freight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string plate_number = 16;</code>
     * @return string
     */
    public function getPlateNumber()
    {
        return $this->plate_number;
    }

    /**
     * Generated from protobuf field <code>string plate_number = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setPlateNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->plate_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ameta = 17;</code>
     * @return string
     */
    public function getAmeta()
    {
        return $this->ameta;
    }

    /**
     * Generated from protobuf field <code>string ameta = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setAmeta($var)
    {
        GPBUtil::checkString($var, True);
        $this->ameta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 update_date = 18;</code>
     * @return int|string
     */
    public function getUpdateDate()
    {
        return $this->update_date;
    }

    /**
     * Generated from protobuf field <code>uint64 update_date = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->update_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cargo_type = 19;</code>
     * @return string
     */
    public function getCargoType()
    {
        return $this->cargo_type;
    }

    /**
     * Generated from protobuf field <code>string cargo_type = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setCargoType($var)
    {
        GPBUtil::checkString($var, True);
        $this->cargo_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string truck_type = 20;</code>
     * @return string
     */
    public function getTruckType()
    {
        return $this->truck_type;
    }

    /**
     * Generated from protobuf field <code>string truck_type = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setTruckType($var)
    {
        GPBUtil::checkString($var, True);
        $this->truck_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string contract_type = 21;</code>
     * @return string
     */
    public function getContractType()
    {
        return $this->contract_type;
    }

    /**
     * Generated from protobuf field <code>string contract_type = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setContractType($var)
    {
        GPBUtil::checkString($var, True);
        $this->contract_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string adr = 22;</code>
     * @return string
     */
    public function getAdr()
    {
        return $this->adr;
    }

    /**
     * Generated from protobuf field <code>string adr = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setAdr($var)
    {
        GPBUtil::checkString($var, True);
        $this->adr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Rohel.TruckStop stop = 23;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStop()
    {
        return $this->stop;
    }

    /**
     * Generated from protobuf field <code>repeated .Rohel.TruckStop stop = 23;</code>
     * @param \Rohel\TruckStop[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStop($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rohel\TruckStop::class);
        $this->stop = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 creation_date = 24;</code>
     * @return int|string
     */
    public function getCreationDate()
    {
        return $this->creation_date;
    }

    /**
     * Generated from protobuf field <code>uint64 creation_date = 24;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreationDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->creation_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status_changed_by = 25;</code>
     * @return int
     */
    public function getStatusChangedBy()
    {
        return $this->status_changed_by;
    }

    /**
     * Generated from protobuf field <code>int32 status_changed_by = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setStatusChangedBy($var)
    {
        GPBUtil::checkInt32($var);
        $this->status_changed_by = $var;

        return $this;
    }

}

