<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Rohel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rohel.TruckStop</code>
 */
class TruckStop extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string city = 2;</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>int32 cmr = 3;</code>
     */
    protected $cmr = 0;
    /**
     * Generated from protobuf field <code>float loading_meters = 4;</code>
     */
    protected $loading_meters = 0.0;
    /**
     * Generated from protobuf field <code>float weight = 5;</code>
     */
    protected $weight = 0.0;
    /**
     * Generated from protobuf field <code>float volume = 6;</code>
     */
    protected $volume = 0.0;
    /**
     * Generated from protobuf field <code>int32 stop_id = 7;</code>
     */
    protected $stop_id = 0;
    /**
     * Generated from protobuf field <code>int32 truck_id = 8;</code>
     */
    protected $truck_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $city
     *     @type int $cmr
     *     @type float $loading_meters
     *     @type float $weight
     *     @type float $volume
     *     @type int $stop_id
     *     @type int $truck_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 2;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cmr = 3;</code>
     * @return int
     */
    public function getCmr()
    {
        return $this->cmr;
    }

    /**
     * Generated from protobuf field <code>int32 cmr = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCmr($var)
    {
        GPBUtil::checkInt32($var);
        $this->cmr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float loading_meters = 4;</code>
     * @return float
     */
    public function getLoadingMeters()
    {
        return $this->loading_meters;
    }

    /**
     * Generated from protobuf field <code>float loading_meters = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setLoadingMeters($var)
    {
        GPBUtil::checkFloat($var);
        $this->loading_meters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float weight = 5;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>float weight = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float volume = 6;</code>
     * @return float
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>float volume = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkFloat($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 stop_id = 7;</code>
     * @return int
     */
    public function getStopId()
    {
        return $this->stop_id;
    }

    /**
     * Generated from protobuf field <code>int32 stop_id = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkInt32($var);
        $this->stop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 truck_id = 8;</code>
     * @return int
     */
    public function getTruckId()
    {
        return $this->truck_id;
    }

    /**
     * Generated from protobuf field <code>int32 truck_id = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setTruckId($var)
    {
        GPBUtil::checkInt32($var);
        $this->truck_id = $var;

        return $this;
    }

}

