<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Rohel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rohel.TruckMatch</code>
 */
class TruckMatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string operator = 2;</code>
     */
    protected $operator = '';
    /**
     * Generated from protobuf field <code>int32 status = 3;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string from_city = 4;</code>
     */
    protected $from_city = '';
    /**
     * Generated from protobuf field <code>uint64 availability = 5;</code>
     */
    protected $availability = 0;
    /**
     * Generated from protobuf field <code>string plate_number = 6;</code>
     */
    protected $plate_number = '';
    /**
     * Generated from protobuf field <code>string ameta = 7;</code>
     */
    protected $ameta = '';
    /**
     * Generated from protobuf field <code>string order_type = 8;</code>
     */
    protected $order_type = '';
    /**
     * Generated from protobuf field <code>string adr = 9;</code>
     */
    protected $adr = '';
    /**
     * Generated from protobuf field <code>uint64 item_date = 10;</code>
     */
    protected $item_date = 0;
    /**
     * Generated from protobuf field <code>int32 item_id = 11;</code>
     */
    protected $item_id = 0;
    /**
     * Generated from protobuf field <code>string item_kind = 12;</code>
     */
    protected $item_kind = '';
    /**
     * Generated from protobuf field <code>float loading_meters = 13;</code>
     */
    protected $loading_meters = 0.0;
    /**
     * Generated from protobuf field <code>float weight = 14;</code>
     */
    protected $weight = 0.0;
    /**
     * Generated from protobuf field <code>float volume = 15;</code>
     */
    protected $volume = 0.0;
    /**
     * Generated from protobuf field <code>string to_city = 16;</code>
     */
    protected $to_city = '';
    /**
     * Generated from protobuf field <code>int32 originator_id = 17;</code>
     */
    protected $originator_id = 0;
    /**
     * Generated from protobuf field <code>int32 recipient_id = 18;</code>
     */
    protected $recipient_id = 0;
    /**
     * Generated from protobuf field <code>string details = 19;</code>
     */
    protected $details = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $operator
     *     @type int $status
     *     @type string $from_city
     *     @type int|string $availability
     *     @type string $plate_number
     *     @type string $ameta
     *     @type string $order_type
     *     @type string $adr
     *     @type int|string $item_date
     *     @type int $item_id
     *     @type string $item_kind
     *     @type float $loading_meters
     *     @type float $weight
     *     @type float $volume
     *     @type string $to_city
     *     @type int $originator_id
     *     @type int $recipient_id
     *     @type string $details
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operator = 2;</code>
     * @return string
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>string operator = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 3;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from_city = 4;</code>
     * @return string
     */
    public function getFromCity()
    {
        return $this->from_city;
    }

    /**
     * Generated from protobuf field <code>string from_city = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFromCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->from_city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 availability = 5;</code>
     * @return int|string
     */
    public function getAvailability()
    {
        return $this->availability;
    }

    /**
     * Generated from protobuf field <code>uint64 availability = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAvailability($var)
    {
        GPBUtil::checkUint64($var);
        $this->availability = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string plate_number = 6;</code>
     * @return string
     */
    public function getPlateNumber()
    {
        return $this->plate_number;
    }

    /**
     * Generated from protobuf field <code>string plate_number = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPlateNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->plate_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ameta = 7;</code>
     * @return string
     */
    public function getAmeta()
    {
        return $this->ameta;
    }

    /**
     * Generated from protobuf field <code>string ameta = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAmeta($var)
    {
        GPBUtil::checkString($var, True);
        $this->ameta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_type = 8;</code>
     * @return string
     */
    public function getOrderType()
    {
        return $this->order_type;
    }

    /**
     * Generated from protobuf field <code>string order_type = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderType($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string adr = 9;</code>
     * @return string
     */
    public function getAdr()
    {
        return $this->adr;
    }

    /**
     * Generated from protobuf field <code>string adr = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setAdr($var)
    {
        GPBUtil::checkString($var, True);
        $this->adr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 item_date = 10;</code>
     * @return int|string
     */
    public function getItemDate()
    {
        return $this->item_date;
    }

    /**
     * Generated from protobuf field <code>uint64 item_date = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setItemDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->item_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 item_id = 11;</code>
     * @return int
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * Generated from protobuf field <code>int32 item_id = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkInt32($var);
        $this->item_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string item_kind = 12;</code>
     * @return string
     */
    public function getItemKind()
    {
        return $this->item_kind;
    }

    /**
     * Generated from protobuf field <code>string item_kind = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setItemKind($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float loading_meters = 13;</code>
     * @return float
     */
    public function getLoadingMeters()
    {
        return $this->loading_meters;
    }

    /**
     * Generated from protobuf field <code>float loading_meters = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setLoadingMeters($var)
    {
        GPBUtil::checkFloat($var);
        $this->loading_meters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float weight = 14;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>float weight = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float volume = 15;</code>
     * @return float
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>float volume = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkFloat($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to_city = 16;</code>
     * @return string
     */
    public function getToCity()
    {
        return $this->to_city;
    }

    /**
     * Generated from protobuf field <code>string to_city = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setToCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 originator_id = 17;</code>
     * @return int
     */
    public function getOriginatorId()
    {
        return $this->originator_id;
    }

    /**
     * Generated from protobuf field <code>int32 originator_id = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginatorId($var)
    {
        GPBUtil::checkInt32($var);
        $this->originator_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 recipient_id = 18;</code>
     * @return int
     */
    public function getRecipientId()
    {
        return $this->recipient_id;
    }

    /**
     * Generated from protobuf field <code>int32 recipient_id = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setRecipientId($var)
    {
        GPBUtil::checkInt32($var);
        $this->recipient_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string details = 19;</code>
     * @return string
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>string details = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkString($var, True);
        $this->details = $var;

        return $this;
    }

}

