<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Rohel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rohel.TruckUpdates</code>
 */
class TruckUpdates extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>bool operator = 2;</code>
     */
    protected $operator = false;
    /**
     * Generated from protobuf field <code>bool originator = 3;</code>
     */
    protected $originator = false;
    /**
     * Generated from protobuf field <code>bool recipient = 4;</code>
     */
    protected $recipient = false;
    /**
     * Generated from protobuf field <code>bool accepted_by = 5;</code>
     */
    protected $accepted_by = false;
    /**
     * Generated from protobuf field <code>bool status = 6;</code>
     */
    protected $status = false;
    /**
     * Generated from protobuf field <code>bool from_city = 7;</code>
     */
    protected $from_city = false;
    /**
     * Generated from protobuf field <code>bool from_address = 8;</code>
     */
    protected $from_address = false;
    /**
     * Generated from protobuf field <code>bool loading_date = 9;</code>
     */
    protected $loading_date = false;
    /**
     * Generated from protobuf field <code>bool unloading_date = 10;</code>
     */
    protected $unloading_date = false;
    /**
     * Generated from protobuf field <code>bool availability = 11;</code>
     */
    protected $availability = false;
    /**
     * Generated from protobuf field <code>bool acceptance = 12;</code>
     */
    protected $acceptance = false;
    /**
     * Generated from protobuf field <code>bool expiration = 13;</code>
     */
    protected $expiration = false;
    /**
     * Generated from protobuf field <code>bool details = 14;</code>
     */
    protected $details = false;
    /**
     * Generated from protobuf field <code>bool freight = 15;</code>
     */
    protected $freight = false;
    /**
     * Generated from protobuf field <code>bool plate_number = 16;</code>
     */
    protected $plate_number = false;
    /**
     * Generated from protobuf field <code>bool ameta = 17;</code>
     */
    protected $ameta = false;
    /**
     * Generated from protobuf field <code>bool cargo_type = 19;</code>
     */
    protected $cargo_type = false;
    /**
     * Generated from protobuf field <code>bool truck_type = 20;</code>
     */
    protected $truck_type = false;
    /**
     * Generated from protobuf field <code>bool contract_type = 21;</code>
     */
    protected $contract_type = false;
    /**
     * Generated from protobuf field <code>bool adr = 18;</code>
     */
    protected $adr = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type bool $operator
     *     @type bool $originator
     *     @type bool $recipient
     *     @type bool $accepted_by
     *     @type bool $status
     *     @type bool $from_city
     *     @type bool $from_address
     *     @type bool $loading_date
     *     @type bool $unloading_date
     *     @type bool $availability
     *     @type bool $acceptance
     *     @type bool $expiration
     *     @type bool $details
     *     @type bool $freight
     *     @type bool $plate_number
     *     @type bool $ameta
     *     @type bool $cargo_type
     *     @type bool $truck_type
     *     @type bool $contract_type
     *     @type bool $adr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool operator = 2;</code>
     * @return bool
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>bool operator = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkBool($var);
        $this->operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool originator = 3;</code>
     * @return bool
     */
    public function getOriginator()
    {
        return $this->originator;
    }

    /**
     * Generated from protobuf field <code>bool originator = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setOriginator($var)
    {
        GPBUtil::checkBool($var);
        $this->originator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool recipient = 4;</code>
     * @return bool
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     * Generated from protobuf field <code>bool recipient = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRecipient($var)
    {
        GPBUtil::checkBool($var);
        $this->recipient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool accepted_by = 5;</code>
     * @return bool
     */
    public function getAcceptedBy()
    {
        return $this->accepted_by;
    }

    /**
     * Generated from protobuf field <code>bool accepted_by = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setAcceptedBy($var)
    {
        GPBUtil::checkBool($var);
        $this->accepted_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool status = 6;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>bool status = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool from_city = 7;</code>
     * @return bool
     */
    public function getFromCity()
    {
        return $this->from_city;
    }

    /**
     * Generated from protobuf field <code>bool from_city = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setFromCity($var)
    {
        GPBUtil::checkBool($var);
        $this->from_city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool from_address = 8;</code>
     * @return bool
     */
    public function getFromAddress()
    {
        return $this->from_address;
    }

    /**
     * Generated from protobuf field <code>bool from_address = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setFromAddress($var)
    {
        GPBUtil::checkBool($var);
        $this->from_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool loading_date = 9;</code>
     * @return bool
     */
    public function getLoadingDate()
    {
        return $this->loading_date;
    }

    /**
     * Generated from protobuf field <code>bool loading_date = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setLoadingDate($var)
    {
        GPBUtil::checkBool($var);
        $this->loading_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool unloading_date = 10;</code>
     * @return bool
     */
    public function getUnloadingDate()
    {
        return $this->unloading_date;
    }

    /**
     * Generated from protobuf field <code>bool unloading_date = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setUnloadingDate($var)
    {
        GPBUtil::checkBool($var);
        $this->unloading_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool availability = 11;</code>
     * @return bool
     */
    public function getAvailability()
    {
        return $this->availability;
    }

    /**
     * Generated from protobuf field <code>bool availability = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setAvailability($var)
    {
        GPBUtil::checkBool($var);
        $this->availability = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool acceptance = 12;</code>
     * @return bool
     */
    public function getAcceptance()
    {
        return $this->acceptance;
    }

    /**
     * Generated from protobuf field <code>bool acceptance = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setAcceptance($var)
    {
        GPBUtil::checkBool($var);
        $this->acceptance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool expiration = 13;</code>
     * @return bool
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>bool expiration = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkBool($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool details = 14;</code>
     * @return bool
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>bool details = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkBool($var);
        $this->details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool freight = 15;</code>
     * @return bool
     */
    public function getFreight()
    {
        return $this->freight;
    }

    /**
     * Generated from protobuf field <code>bool freight = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setFreight($var)
    {
        GPBUtil::checkBool($var);
        $this->freight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool plate_number = 16;</code>
     * @return bool
     */
    public function getPlateNumber()
    {
        return $this->plate_number;
    }

    /**
     * Generated from protobuf field <code>bool plate_number = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setPlateNumber($var)
    {
        GPBUtil::checkBool($var);
        $this->plate_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ameta = 17;</code>
     * @return bool
     */
    public function getAmeta()
    {
        return $this->ameta;
    }

    /**
     * Generated from protobuf field <code>bool ameta = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setAmeta($var)
    {
        GPBUtil::checkBool($var);
        $this->ameta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool cargo_type = 19;</code>
     * @return bool
     */
    public function getCargoType()
    {
        return $this->cargo_type;
    }

    /**
     * Generated from protobuf field <code>bool cargo_type = 19;</code>
     * @param bool $var
     * @return $this
     */
    public function setCargoType($var)
    {
        GPBUtil::checkBool($var);
        $this->cargo_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool truck_type = 20;</code>
     * @return bool
     */
    public function getTruckType()
    {
        return $this->truck_type;
    }

    /**
     * Generated from protobuf field <code>bool truck_type = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setTruckType($var)
    {
        GPBUtil::checkBool($var);
        $this->truck_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool contract_type = 21;</code>
     * @return bool
     */
    public function getContractType()
    {
        return $this->contract_type;
    }

    /**
     * Generated from protobuf field <code>bool contract_type = 21;</code>
     * @param bool $var
     * @return $this
     */
    public function setContractType($var)
    {
        GPBUtil::checkBool($var);
        $this->contract_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool adr = 18;</code>
     * @return bool
     */
    public function getAdr()
    {
        return $this->adr;
    }

    /**
     * Generated from protobuf field <code>bool adr = 18;</code>
     * @param bool $var
     * @return $this
     */
    public function setAdr($var)
    {
        GPBUtil::checkBool($var);
        $this->adr = $var;

        return $this;
    }

}

