<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Rohel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rohel.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string username = 2;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>string password = 3;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>int32 class = 4;</code>
     */
    protected $class = 0;
    /**
     * Generated from protobuf field <code>int32 insert = 5;</code>
     */
    protected $insert = 0;
    /**
     * Generated from protobuf field <code>int32 reports = 6;</code>
     */
    protected $reports = 0;
    /**
     * Generated from protobuf field <code>int32 turkey = 7;</code>
     */
    protected $turkey = 0;
    /**
     * Generated from protobuf field <code>int32 greece = 8;</code>
     */
    protected $greece = 0;
    /**
     * Generated from protobuf field <code>int32 serbia = 9;</code>
     */
    protected $serbia = 0;
    /**
     * Generated from protobuf field <code>int32 moldova = 10;</code>
     */
    protected $moldova = 0;
    /**
     * Generated from protobuf field <code>int32 romania = 11;</code>
     */
    protected $romania = 0;
    /**
     * Generated from protobuf field <code>string filter = 12;</code>
     */
    protected $filter = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $username
     *     @type string $password
     *     @type int $class
     *     @type int $insert
     *     @type int $reports
     *     @type int $turkey
     *     @type int $greece
     *     @type int $serbia
     *     @type int $moldova
     *     @type int $romania
     *     @type string $filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 class = 4;</code>
     * @return int
     */
    public function getClass()
    {
        return $this->class;
    }

    /**
     * Generated from protobuf field <code>int32 class = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setClass($var)
    {
        GPBUtil::checkInt32($var);
        $this->class = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 insert = 5;</code>
     * @return int
     */
    public function getInsert()
    {
        return $this->insert;
    }

    /**
     * Generated from protobuf field <code>int32 insert = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setInsert($var)
    {
        GPBUtil::checkInt32($var);
        $this->insert = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 reports = 6;</code>
     * @return int
     */
    public function getReports()
    {
        return $this->reports;
    }

    /**
     * Generated from protobuf field <code>int32 reports = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setReports($var)
    {
        GPBUtil::checkInt32($var);
        $this->reports = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 turkey = 7;</code>
     * @return int
     */
    public function getTurkey()
    {
        return $this->turkey;
    }

    /**
     * Generated from protobuf field <code>int32 turkey = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setTurkey($var)
    {
        GPBUtil::checkInt32($var);
        $this->turkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 greece = 8;</code>
     * @return int
     */
    public function getGreece()
    {
        return $this->greece;
    }

    /**
     * Generated from protobuf field <code>int32 greece = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setGreece($var)
    {
        GPBUtil::checkInt32($var);
        $this->greece = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 serbia = 9;</code>
     * @return int
     */
    public function getSerbia()
    {
        return $this->serbia;
    }

    /**
     * Generated from protobuf field <code>int32 serbia = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setSerbia($var)
    {
        GPBUtil::checkInt32($var);
        $this->serbia = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 moldova = 10;</code>
     * @return int
     */
    public function getMoldova()
    {
        return $this->moldova;
    }

    /**
     * Generated from protobuf field <code>int32 moldova = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setMoldova($var)
    {
        GPBUtil::checkInt32($var);
        $this->moldova = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 romania = 11;</code>
     * @return int
     */
    public function getRomania()
    {
        return $this->romania;
    }

    /**
     * Generated from protobuf field <code>int32 romania = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setRomania($var)
    {
        GPBUtil::checkInt32($var);
        $this->romania = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string filter = 12;</code>
     * @return string
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * Generated from protobuf field <code>string filter = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter = $var;

        return $this;
    }

}

