<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Rohel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rohel.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string username = 2;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>string password = 3;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>int32 class = 4;</code>
     */
    protected $class = 0;
    /**
     * Generated from protobuf field <code>int32 insert = 5;</code>
     */
    protected $insert = 0;
    /**
     * Generated from protobuf field <code>int32 reports = 6;</code>
     */
    protected $reports = 0;
    /**
     * Generated from protobuf field <code>int32 country_id = 7;</code>
     */
    protected $country_id = 0;
    /**
     * Generated from protobuf field <code>string name = 8;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string office = 9;</code>
     */
    protected $office = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $username
     *     @type string $password
     *     @type int $class
     *     @type int $insert
     *     @type int $reports
     *     @type int $country_id
     *     @type string $name
     *     @type string $office
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 class = 4;</code>
     * @return int
     */
    public function getClass()
    {
        return $this->class;
    }

    /**
     * Generated from protobuf field <code>int32 class = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setClass($var)
    {
        GPBUtil::checkInt32($var);
        $this->class = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 insert = 5;</code>
     * @return int
     */
    public function getInsert()
    {
        return $this->insert;
    }

    /**
     * Generated from protobuf field <code>int32 insert = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setInsert($var)
    {
        GPBUtil::checkInt32($var);
        $this->insert = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 reports = 6;</code>
     * @return int
     */
    public function getReports()
    {
        return $this->reports;
    }

    /**
     * Generated from protobuf field <code>int32 reports = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setReports($var)
    {
        GPBUtil::checkInt32($var);
        $this->reports = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 country_id = 7;</code>
     * @return int
     */
    public function getCountryId()
    {
        return $this->country_id;
    }

    /**
     * Generated from protobuf field <code>int32 country_id = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setCountryId($var)
    {
        GPBUtil::checkInt32($var);
        $this->country_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 8;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string office = 9;</code>
     * @return string
     */
    public function getOffice()
    {
        return $this->office;
    }

    /**
     * Generated from protobuf field <code>string office = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setOffice($var)
    {
        GPBUtil::checkString($var, True);
        $this->office = $var;

        return $this;
    }

}

