<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace GPBMetadata;

class Types
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ø
types.protoRohel"Ú
Request

id (
operator (	

originator (
client (	
	from_city (	
from_address (	
to_city (	

to_address (	
loading_date	 (
unloading_date
 (
description (	
collies (	
weight (
volume (
loading_meters (
freight (
instructions (	

acceptance (

expiration (
plate_number (	
ameta (	

order_type (	
adr (	
	recipient (
status (
accepted_by (	"˘
RequestUpdates

id (
operator (

originator (
client (
	from_city (
from_address (
to_city (

to_address (
loading_date	 (
unloading_date
 (
description (
collies (
weight (
volume (
loading_meters (
freight (
instructions (

acceptance (

expiration (
plate_number (
ameta (

order_type (
adr (
	recipient (
status (
accepted_by ("Õ
Truck

id (
operator (	

originator (
	recipient (
accepted_by (	
status (
	from_city (	
from_address (	
loading_date	 (
unloading_date
 (
availability (

acceptance (

expiration (
details (	
freight (
plate_number (	
ameta (	

order_type (	

cargo_type (	

truck_type (	
contract_type (	
adr (	
stop (2.Rohel.TruckStop"¥
TruckUpdates

id (
operator (

originator (
	recipient (
accepted_by (
status (
	from_city (
from_address (
loading_date	 (
unloading_date
 (
availability (

acceptance (

expiration (
details (
freight (
plate_number (
ameta (

order_type (

cargo_type (

truck_type (
contract_type (
adr ("ç
	TruckStop

id (
city (	
cmr (
loading_meters (
weight (
volume (
stop_id (
truck_id ("à
User

id (
username (	
password (	
class (
insert (
reports (

country_id (
name (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

